# fly.toml app configuration file generated for anhao-elysia on 2024-07-10T21:31:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anhao-elysia-testing'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256m'
  cpu_kind = 'shared'
  cpus = 1
