# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy to Testing
on:
  push:
    branches:
      - testing
jobs:
  deploy:
    name: Deploy to Testing
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.testing.tomal
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_TESTING }}
